---
# tasks file for ansible-role-openvpn - client up
- name: Configuration IP forwarding
  sysctl:
    name: "{{ openvpn_forwarding_name }}"
    value: "{{ openvpn_forwarding_value }}"
    state: present

- name: Add ufw/before.rules content
  blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    content: "{{ openvpn_ufw_before_rules_content }}"

- name: Customize ufw forwarding policy
  lineinfile:
    path: "/etc/default/ufw"
    line: "DEFAULT_FORWARD_POLICY=\"ACCEPT\""
    regexp: "^DEFAULT_FORWARD_POLICY="

- name: Open ufw ports for openvpn and ssh
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items:
    - { port: 'ssh', protocol: 'tcp' }
    - { port: 'openvpn', protocol: 'udp' }

- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: allow

- name: Start openvpn systemd service
  systemd:
    name: openvpn@server
    state: started
    daemon_reload: yes
    enabled: yes
